name: my_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^6.1.0
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.5.0
  http: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: false
  ios: false
  image_path: "assets/images/logo2.png"
  web:
    generate: true
    image_path: "assets/images/logo2.png"
    background_color: "#0b0d2c"
    theme_color: "#0b0d2c"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/projects.json
    - assets/certificates.json
    - assets/certificates/
